export const ar = {
  appName: 'نظام إدارة الديون',
  login: 'تسجيل الدخول',
  register: 'إنشاء حساب',
  logout: 'تسجيل الخروج',
  email: 'البريد الإلكتروني',
  password: 'كلمة المرور',
  name: 'الاسم',
  phone: 'رقم الهاتف',
  address: 'العنوان',
  notes: 'ملاحظات',
  dashboard: 'لوحة التحكم',
  customers: 'العملاء',
  debts: 'الديون',
  payments: 'المدفوعات',
  addCustomer: 'إضافة عميل',
  editCustomer: 'تعديل العميل',
  deleteCustomer: 'حذف العميل',
  addDebt: 'إضافة دين',
  addPayment: 'تسجيل دفعة',
  search: 'بحث',
  totalDebts: 'إجمالي الديون',
  totalPaid: 'إجمالي المدفوعات',
  outstanding: 'المبالغ المتبقية',
  activeCustomers: 'العملاء النشطون',
  activeDebts: 'الديون النشطة',
  remaining: 'المتبقي',
  amount: 'المبلغ',
  description: 'الوصف',
  status: 'الحالة',
  active: 'نشط',
  paid: 'مسدد',
  save: 'حفظ',
  cancel: 'إلغاء',
  delete: 'حذف',
  confirm: 'تأكيد',
  loading: 'جاري التحميل...',
  noData: 'لا توجد بيانات',
  error: 'حدث خطأ',
  success: 'تم بنجاح',
  customerDeleted: 'تم حذف العميل بنجاح',
  debtAdded: 'تم إضافة الدين بنجاح',
  paymentAdded: 'تم تسجيل الدفعة بنجاح',
  customerAdded: 'تم إضافة العميل بنجاح',
  currency: 'د.ج',
  blog: 'المدونة',
  noArticles: 'لا توجد مقالات',
  backToBlog: 'العودة إلى المدونة',
  notFound: 'الصفحة غير موجودة',
};
